"""

Revision ID: c3628dc864f7
Revises: 25d12fb63ced
Create Date: 2026-09-19 11:46:51.741266

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c3628dc864f7"
down_revision: str | Sequence[str] | None = "25d12fb63ced"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
