"""

Revision ID: e35634bf53ec
Revises: c3628dc864f7
Create Date: 2026-09-19 12:11:24.055825

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "e35634bf53ec"
down_revision: str | Sequence[str] | None = "c3628dc864f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
